/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as NewMissionRouteImport } from './routes/new-mission'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KidCreatedRouteImport } from './routes/kid-created'
import { Route as FamilyNameRouteImport } from './routes/family-name'
import { Route as FamilyCodeRouteImport } from './routes/family-code'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AddKidRouteImport } from './routes/add-kid'
import { Route as IndexRouteImport } from './routes/index'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const NewMissionRoute = NewMissionRouteImport.update({
  id: '/new-mission',
  path: '/new-mission',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KidCreatedRoute = KidCreatedRouteImport.update({
  id: '/kid-created',
  path: '/kid-created',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyNameRoute = FamilyNameRouteImport.update({
  id: '/family-name',
  path: '/family-name',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyCodeRoute = FamilyCodeRouteImport.update({
  id: '/family-code',
  path: '/family-code',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AddKidRoute = AddKidRouteImport.update({
  id: '/add-kid',
  path: '/add-kid',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-kid': typeof AddKidRoute
  '/dashboard': typeof DashboardRoute
  '/family-code': typeof FamilyCodeRoute
  '/family-name': typeof FamilyNameRoute
  '/kid-created': typeof KidCreatedRoute
  '/login': typeof LoginRoute
  '/new-mission': typeof NewMissionRoute
  '/signup': typeof SignupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-kid': typeof AddKidRoute
  '/dashboard': typeof DashboardRoute
  '/family-code': typeof FamilyCodeRoute
  '/family-name': typeof FamilyNameRoute
  '/kid-created': typeof KidCreatedRoute
  '/login': typeof LoginRoute
  '/new-mission': typeof NewMissionRoute
  '/signup': typeof SignupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-kid': typeof AddKidRoute
  '/dashboard': typeof DashboardRoute
  '/family-code': typeof FamilyCodeRoute
  '/family-name': typeof FamilyNameRoute
  '/kid-created': typeof KidCreatedRoute
  '/login': typeof LoginRoute
  '/new-mission': typeof NewMissionRoute
  '/signup': typeof SignupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add-kid'
    | '/dashboard'
    | '/family-code'
    | '/family-name'
    | '/kid-created'
    | '/login'
    | '/new-mission'
    | '/signup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add-kid'
    | '/dashboard'
    | '/family-code'
    | '/family-name'
    | '/kid-created'
    | '/login'
    | '/new-mission'
    | '/signup'
  id:
    | '__root__'
    | '/'
    | '/add-kid'
    | '/dashboard'
    | '/family-code'
    | '/family-name'
    | '/kid-created'
    | '/login'
    | '/new-mission'
    | '/signup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddKidRoute: typeof AddKidRoute
  DashboardRoute: typeof DashboardRoute
  FamilyCodeRoute: typeof FamilyCodeRoute
  FamilyNameRoute: typeof FamilyNameRoute
  KidCreatedRoute: typeof KidCreatedRoute
  LoginRoute: typeof LoginRoute
  NewMissionRoute: typeof NewMissionRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-mission': {
      id: '/new-mission'
      path: '/new-mission'
      fullPath: '/new-mission'
      preLoaderRoute: typeof NewMissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kid-created': {
      id: '/kid-created'
      path: '/kid-created'
      fullPath: '/kid-created'
      preLoaderRoute: typeof KidCreatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family-name': {
      id: '/family-name'
      path: '/family-name'
      fullPath: '/family-name'
      preLoaderRoute: typeof FamilyNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family-code': {
      id: '/family-code'
      path: '/family-code'
      fullPath: '/family-code'
      preLoaderRoute: typeof FamilyCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-kid': {
      id: '/add-kid'
      path: '/add-kid'
      fullPath: '/add-kid'
      preLoaderRoute: typeof AddKidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddKidRoute: AddKidRoute,
  DashboardRoute: DashboardRoute,
  FamilyCodeRoute: FamilyCodeRoute,
  FamilyNameRoute: FamilyNameRoute,
  KidCreatedRoute: KidCreatedRoute,
  LoginRoute: LoginRoute,
  NewMissionRoute: NewMissionRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
